### ISSUE TITLE
Block write access to specific channels

### ISSUE THREAD

**Issue by jgprogramming** [kmisztal/JImageStream#1]
add .channel() operation to ImageStream that restricts write access to channels specified in arguments (per filter, like predicate)

**Comment by kmisztal** [comment]
I wonder if you could also write a function which can offer for example stream with: (r+g+b)/3, or other function/form? maybe same functional interface?

**Comment by jgprogramming** [comment]
It's possible, but I don't think it's really related to this issue. It's more of a new Collector for function interface that provides double function(Point p) or extension of Filter if I understand correctly. I'm going to create new issue for this after collector interface is implemented.

**Comment by kmisztal** [comment]
OK, move this to new issue
