### ISSUE TITLE
Add support for parallel stream in ImageStream 

### ISSUE THREAD

**Issue by jgprogramming** [kmisztal/JImageStream#2]
.parallelStream() executes Filter in parallel (thread per line of image) - investigate good value for default amount of threads
.setThreads(int) allows to set amount of worked thread (per filter, like predicate)
.parallelStream(int) - sets default value for setThreads for all filters in this stream

.parallelStream().setThreads(50).apply(new Filter()).setThreads(1).apply(SecondFilter).collect() is possible

**Comment by Grebosz** [comment]
What about ColorModel when creating BufferedImage from workingRaster in apply method?
Should be it like in collect to get color model of originalImage? Or ColorModel.getRGBdefault?

**Comment by jgprogramming** [comment]
note this commit https://github.com/jgprogramming/KiMageAPI/commit/d6477df5cf676ff7464f3c802cfbc12645d2bb3e - it changed the way we use bufferedImage. There's no need to make copies of bufferedImage per filter since it's moved to Filter class in .setSource(BufferedImage) .saveToImage(BufferedImage) methods.

**Comment by kmisztal** [comment]
.setThreads(int) 
Please prepare also the way to use the default number of thread which would be equal to number of cores in CPU
