### ISSUE TITLE
Documentation don't work !!!

### ISSUE THREAD

**Issue by slaby93** [kmisztal/JImageStream#23]

**Comment by slaby93** [comment]
Documentation needs to be available online.
I don't know and I don't need to know how to open . adoc file. That's why Github provides support for .md files.

Also there is almost no code examples. Please provide some to at least show how to do certain things.

**Comment by jgprogramming** [comment]
documentation will be available on release/1.0.0 in December. For now all we can offer you is w.i.p documentation in our jis-documentation module. To generate it just run mvn clean install on project and you can find it in jis-documentation/target/docs folder

**Comment by jgprogramming** [comment]
here you go https://kmisztal.github.io/JImageStream/
