### ISSUE TITLE
implement arithmetic filters

### ISSUE THREAD

**Issue by jgprogramming** [kmisztal/JImageStream#45]
- implement invert/sum/sub filters
- update documentation with use example

**Comment by HawkeApache** [comment]
@jgprogramming  What do You think about this proposition of SumFilter

[https://github.com/HawkeApache/JImageStream/commit/3760b2d9b925ea6bf3960cc1ee0c53d9dbff032a](url)

**Comment by jgprogramming** [comment]
As long as it works and has a documentation entry it should be fine. This question belongs in pull request tho, issues are for the concept more than implementation.

**Comment by jgprogramming** [comment]
resolved
